### ISSUE TITLE
Crash on start on Android 12

### ISSUE THREAD

**Issue by imongithubnow** [pilot51/voicenotify#85] opened 2022-08-07 14:41 UTC
crDroid 8.7
Android 12
rooted
Crash on start, this is log:
https://paste.crdroid.net/ekSXZX
1.1.3  version works well

**Comment by pilot51** [comment] 2022-08-07 22:50
Duplicate of #84. Fixed in [v1.2.1](https://github.com/pilot51/voicenotify/releases/tag/v1.2.1) which was released a couple hours ago.

**Closed by pilot51** 2022-08-07 22:50 UTC
Labels: bug, duplicate, regression
