### ISSUE TITLE
Keep Screen Off when VN read notifications

### ISSUE THREAD

**Issue by poustchi** [pilot51/voicenotify#43] opened 2014-12-12 20:02 UTC
When VN receives a notification and start reading it, my screen turns ON. Is there any way I can disable such behavior? I do not want the screen to turn ON when VN reading the notifications.
Please advise me.

Android : 4.2.2

**Comment by pilot51** [comment] 2017-11-14 02:14
I suspect this issue was likely caused by a modified version of Accessibility, similar to other issues experienced with some Samsung devices.

Since VN no longer uses Accessibility in favor of Notification Listener (as of 682bbb75), and given the lack of requested info, I'm closing this issue.

**Closed by pilot51** 2017-11-14 02:14 UTC
Labels: bug, can't reproduce, need info
