### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by toas-koas** [pilot51/voicenotify#84] opened 2022-08-04 07:21 UTC
When I start the app, it immediately crashes again.

Pixel 2XL
Android 12
19-20220612-microG-taimen
com.pilot51.voicenotify Version 1.2.0

**Comment by pilot51** [comment] 2022-08-04 12:43
Did you update an existing installation? If so and if you don't mind losing your settings, could you go to the Voice Notify app info in Android settings and clear data and try launching the app again?

**Comment by tibbsbrookside** [comment] 2022-08-04 13:10
I have the same problem with a new install of the latest version from F-Droid on two devices.

Moto G8 Plus. Android 10 (stock ROM)
Samsung Galaxy Tab S2. Android 10 (custom ROM)

**Comment by toas-koas** [comment] 2022-08-04 13:12
I have reinstalled it.
I just tried the old version. It seems to work.
With the current version, I have now discovered an error message when I start it:

`Error: text-to-speech could not be initialised.`

**Comment by pilot51** [comment] 2022-08-04 13:52
Sounds like a duplicate of #80 which I've been unable to reproduce in emulators or my Moto x4 with Android 9.

v1.2.0 is basically to get something out the door and republish it on Google Play (which has been in review for the last 5 days). Far from perfect but I hope it gets the ball rolling on this whole motivation thing.

**Comment by tibbsbrookside** [comment] 2022-08-04 15:05
Here's a logcat extract from my Moto G8 Plus if it helps:
https://pastebin.com/QMBv6M6N

**Comment by pilot51** [comment] 2022-08-04 16:16
Thanks, logcats are definitely helpful!

Appears to be caused by an NPE at [Common:63](https://github.com/pilot51/voicenotify/blob/cf2fd66b9e7127d58edda3a53a2ca9e371856972/app/src/main/java/com/pilot51/voicenotify/Common.kt#L63).

Evidently I wasn't thinking when I converted that function to Kotlin. No idea why I expected that preference to never be null.

I'll fix it probably Friday evening or Saturday (when I have time outside of work).

**Closed** 2022-08-07 01:24 UTC
Labels: bug
