### ISSUE TITLE
Text replacement not occuring.

### ISSUE THREAD

**Issue by famewolf** [pilot51/voicenotify#79] opened 2020-11-03 20:30 UTC
I recently added a third entry into the text replacement page in the app which seems to have stopped all 3 from working at all.

I have the following set:
"Alexa Alexa" to "Alexa"
"Voice Voice" to "Voice"
"Wyze Wyze" to "Wise"  (I'm using a male uk voice from vocalizer tts (Malcolm) and he keeps saying "wiz wiz".

The Wyze one specifically just notified me "person identified on garage cam" which is to be expected as I just parked in the garage but it said the Title twice.  I could adjust the string not to include app but on some apps they do not identify themselves in the actual message.  I'm not sure what to provide you.  Prior to adding that third entry it seemed to work for voice and alexa.

I just tried to modify the test notification so "Voice Notify Content Title" would just be "Voice Notify" and it failed consistently,  Not sure if it's excluded.   I am using the F-Droid version of the app if it matters.

**Comment by pilot51** [comment] 2023-12-31 22:50
Sorry for being 2 years late to this. It looks like the issue is that the text to replace doesn't match the format defined in the TTS Message setting, which is ` #a. #c. #m.` by default. So for the test message, changing "Voice Notify Content Title" to "Voice Notify. Content Title" worked for me. Presumably the same applies to the others and you need a period after the first word.

I'll close this since I'm confident that's the issue, but let me know if you still have the problem and I'll reopen it.

**Closed by pilot51** 2023-12-31 22:50 UTC
Labels: bug
