### ISSUE TITLE
Fails to upgrade from 1.1.3

### ISSUE THREAD

**Issue by X22396** [pilot51/voicenotify#88] opened 2022-08-12 19:48 UTC
I tried from Play Store, but get message after downloading "Cannot upgrade..." With no reason. I cleared cache, and tried again from Play Store, but same result.

I then dl'd from Github site, but now I get 
![Screenshot_20220812-144040_Package installer](https://user-images.githubusercontent.com/70643888/184432171-02c0585c-0327-4c6f-8fb4-b67321afc60d.jpg)

Tried clearing cache again, but no go.  Is there a way to save my settings, so I can reinstall?

**Comment by pilot51** [comment] 2022-08-13 00:40
Someone else had the same issue yesterday and thought they previously downloaded it from GitHub. Apparently they downloaded it from F-Droid, which builds APKs from source with a different signing key, meaning it is not upgrade-compatible with my builds on GitHub (in the [Releases](https://github.com/pilot51/voicenotify/releases) section) and Google Play.

If you don't want to go through the trouble of losing your settings, you'll either need to continue side-loading the builds from F-Droid or jump through some technical hoops with `adb` commands to uninstall without removing data and reinstall. If you're not concerned about the settings, just uninstall and reinstall the Play Store or GitHub version.

I think I'll have to remove the F-Droid button from the README or add a warning next to it now that I'm aware of this issue.

**Comment by X22396** [comment] 2022-08-13 11:23
Thanks for the reply, funny thing is, My work phone updated VN from Play
Store yesterday no issues, which is what prompted me to update my personal
phone.

Both phones were running same version 1.1.3. however, my personal phone
couldn't find VN on Playstore, I had to search for it using Pilot51. It did
find it, and said "installed" on Play Store.

Another issue, after downloading 1.2.1 from your GitHub site, I uninstalled
1.1.3, then installed 1.2.1, only for it not to find all the apps on my
phone.

I eventually had to go back to 1.1.3 to get everything working properly.

I will play around with it some more.

BTW, I really like VN and have been using it for several years now. This is
my 4th phone and VN is one of my core apps. I love having all my email,
texts, and weather read to me.  I am surprised this has not been
incorporated into Android OS. Thanks for your hard work.

Doug.

**Comment by X22396** [comment] 2022-08-14 13:57
Okay, so I downloaded Voice Notify 1.2.1 from Github site, installed and
noticed it was missing lots of my apps in the app listing., So I DL'd
v1.1.3, also from github. Installed it and all my apps were back. Resetup
VN, and all was good.

This morning, Play Store said there was an update, V1.2.1, available. So I
let it update, installed, no problem.

I went in and checked the apps listing, and once again lots of apps are
missing, (ex: Calls Black List messaging app, Samsung Health, and nothing
after W's {YouTube, Zoom, etc...}).

I went to use the filter and it kicked me out of VN with the error message
attached.

Doug Stratton Jr.
469-251-0613

**Comment by pilot51** [comment] 2022-08-16 02:39
The app list issue was fixed with #89 and the filter crash was also fixed. v1.2.2 is on GitHub now and should be live on the Play Store soon.

The missing apps were caused by a new `QUERY_ALL_PACKAGES` permission I didn't notice that only affected apps targeting and running on Android 11+. That explains why v1.1.3 worked fine (targeting Android 8.1) and why I didn't have the issue on my Android 9 phone. It wasn't obvious on emulators because most system apps appear without the permission and the only manually installed app was Voice Notify, which of course has permission to see itself.

**Closed by pilot51** 2022-08-16 02:39 UTC

**Comment by X22396** [comment] 2022-08-16 10:28
Just installed v1.2.2, and it fixed the issues I had. Thank you VERY MUCH, for your quick response, and update to the app.
