### ISSUE TITLE
Text to speech doesn't seem to function at all

### ISSUE THREAD

**Issue by connervieira** [pilot51/voicenotify#80] opened 2021-11-22 04:54 UTC
I'm on LineageOS on a OnePlus 7 Pro, using RHVoice as my TTS provider. It seems like the TTS itself works just fine, as other apps can use it without issue. However, I'm unable to get Voice Notify to read off notifications in any capacity. I have every "device state" enabled for sake of testing. I tried the "Media", "Voice", and "Notification" audio streams, non of which worked (with the volume up of course). However, I noticed that the volume rockers would change depending on the stream. For example, I chose the "Voice" stream, and the volume rockers still changed media volume. Then after creating a test notification, the volume rocker started changing voice volume, but I still couldn't hear the TTS.

I noticed something similar using the notification stream. When I recieved a notification, my music would quiet down, but there would be no TTS. The music would stay quiet until I pickes up the phone and messed with the notification enough to reset the volume.

**Comment by nepomuc** [comment] 2022-04-10 10:48
This app would be sooo useful if it worked :/ Having the same issue here. @pilot51 I would love to be able to use your app. Can I support you with any logs or something?

**Comment by UlyssesZh** [comment] 2022-06-21 10:03
+1. I also have this issue. I also notice that every time I boot my phone, there is a toast telling me that "Voice Notify: failed to initialize text-to-speech" (I don't remember the exact words). Other applications that use TTS just work fine.

**Comment by pilot51** [comment] 2022-08-16 12:49
So far I've been unable to reproduce, but I'll focus on these TTS issues since all other known major issues have been resolved with v1.2.2.

If I can't reproduce, it would be great if someone experiencing any of these issues could join the [Discord](https://discord.gg/W6XxGT8WG3) or [Matrix](https://matrix.to/#/#voicenotify:p51.me) server to help with debugging and testing fixes.

**Comment by pilot51** [comment] 2024-01-01 04:25
I think I fixed it... hopefully. Commit f471efb

I'm planning to release on Google Play tomorrow. If you don't want to wait (who knows how long approval will take), I added a release-signed build to the [auto build release](https://github.com/pilot51/voicenotify/releases/tag/latest).

I'll close this and if we find out it's still a problem, I'll reopen it.

**Closed by pilot51** 2024-01-01 04:25 UTC
Labels: bug
